export const CHAPTER = {
  FETCH_ALL: "FETCH_ALL_CHAPTERS",
  FETCH_CHAPTER: "FETCH_CHAPTER",
  FILTER: "FILTER_CHAPTER",
  PAGINATE: "PAGINATE_CHAPTER",
  LOADING: "LOADING"
}

export default { 
  CHAPTER
}